### PR TITLE
Use simpler Contributte\Console and bin file for console application

### PR DESCRIPTION
**Pull request by TomasVotruba**
DO NOT MERGE pls! It's compared to opened PR, so there is few commits, so merging might actually drop it. I will handle that manually.

Closes: #18

### CODE REVIEW

**Review by filipsuk — APPROVED** [review]
Very nice 👏  
Can you create PR to master branch?

**Comment by TomasVotruba** [comment]
Thank you....

...aaaaaand done!

**Comment by f3l1x** [comment]
@TomasVotruba @filipsuk That's f..ing awesome. 👍  ❤️

**Comment by TomasVotruba** [comment]
@f3l1x Hell yea! Thanks :hugs: 

We should write a post about this console practise, don't you think?

**Comment by f3l1x** [comment]
@TomasVotruba We really should. I'll be on `Spring IO` conference in Barcelona for the next days, but 22th I'm back. 🏠

**Comment by TomasVotruba** [comment]
@f3l1x So I wrote a draft, you can check it here: https://github.com/pehapkari/pehapkari.cz/pull/289

Feel free to send PR directly in it :+1:

**Pull request merged**
